security:
  oauth2:
    client:
      client-id: admin
      client-secret: password
      refresh-token-validity-seconds: 10000
      access-token-validity-seconds: 3600
    resource:
      id: oauth2_id


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?autoReconnect=true&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: <email>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: authentication-microservice
  activemq:
    broker-url: failover://tcp://localhost:61616
    user: admin
    password: admin

jms:
  queue: jms-queue

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

management:
  security:
    enabled: false

flyway:
  enabled: true
  baseline-on-migrate: true


