security:
  oauth2:
    client:
      client-id: admin
      client-secret: password
    resource:
      id: oauth2_id

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?autoReconnect=true&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true


logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081

management:
  security:
    enabled: false

flyway:
  enabled: true
  baseline-on-migrate: true


